---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo
  namespace: staging
spec:
  interval: 5m
  chart:
    spec:
      chart: demo-chart
      version: v0.0.10
      sourceRef:
        kind: HelmRepository
        name: rparmer-tekton
      interval: 1m
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 64Mi
